package shared

import "errors"

var (
	ErrInvalidAuthPayload     = errors.New("Dữ liệu đăng nhập không hợp lệ")
	ErrInvalidCredentials     = errors.New("Email hoặc mật khẩu không đúng")
	ErrEmailNotVerified       = errors.New("Email chưa được xác thực. Vui lòng nhập mã OTP đã gửi về email đăng ký")
	ErrLoginProcessFailed     = errors.New("Không thể xử lý đăng nhập")
	ErrInvalidName            = errors.New("Họ tên không được để trống")
	ErrInvalidRegisterEmail   = errors.New("Email không hợp lệ")
	ErrRegisterEmailMustGmail = errors.New("Email đăng ký phải có đuôi @gmail.com")
	ErrWeakPassword           = errors.New("Mật khẩu phải có ít nhất 8 ký tự")
	ErrEmailAlreadyRegistered = errors.New("Email đã được đăng ký")
	ErrEmailCheckFailed       = errors.New("Không thể xác thực email")
	ErrPasswordHashFailed     = errors.New("Không thể bảo mật mật khẩu")
	ErrCreateAccountFailed    = errors.New("Không thể tạo tài khoản")
	ErrInvalidOTPEmail        = errors.New("Email OTP không hợp lệ")
	ErrOTPEmailNotRegistered  = errors.New("Email này chưa được đăng ký")
	ErrOTPProcessFailed       = errors.New("Không thể xử lý mã xác thực")
	ErrInvalidOTPCode         = errors.New("Mã xác thực không hợp lệ hoặc đã hết hạn")
	ErrPasswordResetQueued    = errors.New("Nếu email tồn tại, chúng tôi đã gửi hướng dẫn đặt lại mật khẩu")
	ErrTokenIssueFailed       = errors.New("Không thể tạo token đăng nhập")
	ErrInvalidRefreshToken    = errors.New("Refresh token không hợp lệ hoặc đã hết hạn")
	ErrMissingBearerToken     = errors.New("Thiếu access token")
	ErrInvalidAccessToken     = errors.New("Access token không hợp lệ hoặc đã hết hạn")
	ErrForbiddenResource      = errors.New("Bạn không có quyền truy cập tài nguyên này")

	ErrInvalidBookingPayload = errors.New("Dữ liệu đặt tour không hợp lệ")
	ErrInvalidFullName       = errors.New("Họ tên không được để trống")
	ErrInvalidPhone          = errors.New("Số điện thoại không hợp lệ")
	ErrInvalidEmail          = errors.New("Email không hợp lệ")
	ErrInvalidAdultCount     = errors.New("Số lượng người lớn phải lớn hơn hoặc bằng 1")
	ErrInvalidChildCount     = errors.New("Số lượng trẻ em không hợp lệ")
	ErrInvalidInfantCount    = errors.New("Số lượng trẻ nhỏ không hợp lệ")
	ErrInvalidQuantity       = errors.New("Số lượng khách phải lớn hơn 0")
	ErrInsufficientSlots     = errors.New("Số chỗ còn lại không đủ cho yêu cầu đặt tour")
	ErrInvalidTravelDate     = errors.New("Ngày đi không hợp lệ")
	ErrTravelDateInPast      = errors.New("Ngày đi không được ở quá khứ")
	ErrTourNotFound          = errors.New("Tour không tồn tại")
	ErrCreateBookingFailed   = errors.New("Không thể tạo đơn đặt tour")
	ErrInvalidUserID         = errors.New("ID người dùng không hợp lệ")
	ErrInvalidBookingID      = errors.New("ID booking không hợp lệ")
	ErrFetchBookingsFailed   = errors.New("Không thể tải danh sách tour đã đặt")
	ErrBookingNotFound       = errors.New("Không tìm thấy booking cần hủy")
	ErrBookingCannotCancel   = errors.New("Booking này đã được hủy trước đó")
	ErrCancelBookingFailed   = errors.New("Không thể hủy booking")
)
